service: beforis

runtime: php55

handlers:
  - url: /(.*.php)$
    script: \1
    secure: always

  - url: /(.*\.(css|dev|eot|html|pem|png|svg|ttf|woff2?))$
    static_files: \1
    upload: .*\.(css|dev|eot|html|pem|png|svg|ttf|woff2?)$
    secure: always

  - url: /images
    static_dir: images
    secure: always

  - url: /docs
    static_dir: docs
    secure: always

  - url: /js
    static_dir: js
    secure: always

  - url: /
    static_files: index.html
    upload: index.html
    secure: always
